version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: eventscrape-postgres
    environment:
      POSTGRES_DB: eventscrape
      POSTGRES_USER: eventscrape
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-eventscrape_prod}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventscrape -d eventscrape"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eventscrape
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: eventscrape-redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eventscrape
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: eventscrape-api
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://eventscrape:${POSTGRES_PASSWORD:-eventscrape_prod}@postgres:5432/eventscrape
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      PORT: 3001
      EXPORT_DIR: /data/exports
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - eventscrape
    restart: unless-stopped
    volumes:
      - export_data:/data/exports

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
      args:
        ADMIN_API_URL: ${ADMIN_API_URL:-http://__HOST__:3001/api}
    container_name: eventscrape-admin
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3001/api}
      NODE_ENV: production
    depends_on:
      - api
    networks:
      - eventscrape
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: eventscrape-worker
    environment:
      DATABASE_URL: postgres://eventscrape:${POSTGRES_PASSWORD:-eventscrape_prod}@postgres:5432/eventscrape
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      PLAYWRIGHT_HEADLESS: "true"
      EXPORT_DIR: /data/exports
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - eventscrape
    restart: unless-stopped
    volumes:
      - export_data:/data/exports

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: eventscrape-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - admin
      - api
    networks:
      - eventscrape
    restart: unless-stopped
    profiles:
      - with-nginx

networks:
  eventscrape:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  export_data:
