version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: eventscrape-postgres
    environment:
      POSTGRES_DB: eventscrape
      POSTGRES_USER: eventscrape
      POSTGRES_PASSWORD: eventscrape_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventscrape -d eventscrape"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eventscrape

  redis:
    image: redis:7-alpine
    container_name: eventscrape-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 512mb --maxmemory-policy noeviction
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eventscrape

  api:
    image: node:18-alpine
    container_name: eventscrape-api
    working_dir: /app
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://eventscrape:eventscrape_dev@postgres:5432/eventscrape
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
      PORT: 3001
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    command: sh -c "npm install -g pnpm && pnpm install && cd apps/api && pnpm db:migrate && pnpm dev"
    networks:
      - eventscrape

  admin:
    image: node:18-alpine
    container_name: eventscrape-admin
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3001/api
      NODE_ENV: development
    depends_on:
      - api
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/admin/node_modules
    command: sh -c "npm install -g pnpm && pnpm install && cd apps/admin && pnpm dev --host 0.0.0.0"
    networks:
      - eventscrape

  worker:
    image: mcr.microsoft.com/playwright:v1.54.0
    container_name: eventscrape-worker
    working_dir: /app/worker
    environment:
      DATABASE_URL: postgres://eventscrape:eventscrape_dev@postgres:5432/eventscrape
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
      PLAYWRIGHT_HEADLESS: "true"
      EXPORT_DIR: /data/exports
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/worker/node_modules
      - export_data:/data/exports
    command: sh -c "npm install -g pnpm && cd /app && pnpm install && cd /app/worker && pnpm dev"
    networks:
      - eventscrape

networks:
  eventscrape:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  export_data: